# Generated by Django 6.0.4 on 2026-05-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='membership',
            field=models.CharField(blank=True, choices=[('basic', 'Basic'), ('premium', 'Premium')], help_text='User membership type (basic or premium)', max_length=7, null=True),
        ),
    ]
