# Generated by Django 6.0.4 on 2026-05-11 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='rating',
        ),
    ]
