# Generated by Django 6.0.4 on 2026-05-11 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0002_remove_anime_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('genre', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('tva', 'TVA'), ('movie', '극장판'), ('ova', 'OVA'), ('etc', '기타')], default='tva', max_length=15)),
                ('age_rating', models.PositiveSmallIntegerField(choices=[(0, 'ALL'), (7, '7세'), (12, '12세'), (15, '15세'), (19, '19세')], default=0)),
                ('is_complete', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='anime',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animes', to='animes.series'),
        ),
    ]
