# Generated by Django 6.0.4 on 2026-05-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0004_alter_series_options_alter_anime_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='age_rating',
        ),
        migrations.RemoveField(
            model_name='series',
            name='description',
        ),
        migrations.RemoveField(
            model_name='series',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='series',
            name='is_complete',
        ),
        migrations.RemoveField(
            model_name='series',
            name='type',
        ),
        migrations.AddField(
            model_name='anime',
            name='age_rating',
            field=models.PositiveSmallIntegerField(choices=[(0, 'ALL'), (7, '7세'), (12, '12세'), (15, '15세'), (19, '19세')], default=0),
        ),
        migrations.AddField(
            model_name='anime',
            name='genres',
            field=models.CharField(blank=True, help_text='Comma-separated genres (e.g., SF, 모험, 개그)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anime',
            name='is_only_on_laftel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anime',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags (e.g., 가족, 로봇, 게임)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='type',
            field=models.CharField(choices=[('tva', 'TVA'), ('movie', '극장판'), ('ova', 'OVA'), ('etc', '기타')], default='tva', max_length=15),
        ),
    ]
