# Generated by Django 6.0.4 on 2026-05-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0006_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='duration',
            field=models.DurationField(default='0 minutes'),
        ),
    ]
