# Generated by Django 6.0.4 on 2026-05-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0007_episode_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='duration',
            field=models.DurationField(default='00:00:00'),
        ),
    ]
